version: '3.8'

services:
  ffc-ahwr-farmer-apply:
    build:
      context: .
      target: production
    image: ffc-ahwr-farmer-apply
    container_name: ffc-ahwr-farmer-apply
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-farmer-apply-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      GOOGLE_TAG_MANAGER_KEY: ${GOOGLE_TAG_MANAGER_KEY}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      SERVICE_URI: http://localhost:3000
