version: "3.8"

services:
  ffc-ahwr-farmer-apply:
    command: npm run start:watch
    build:
      target: development
    image: ffc-ahwr-farmer-apply-development
    environment:
      NODE_ENV: test
    volumes:
      - ./test-output/:/home/node/test-output/

  zap-baseline-scan:
    image: softwaresecurityproject/zap-bare:2.14.0
    command: zap.sh -cmd -quickurl http://ffc-ahwr-farmer-apply:${PORT:-3000} -configfile wrk/config/zap.conf -quickout wrk/test-output/zap-report.html
    depends_on:
      - ffc-ahwr-farmer-apply
    volumes:
      - ./test-output/:/zap/wrk/test-output/
      - ./zap/:/zap/wrk/config/
    