# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-ahwr-farmer-apply:
    build:
      target: development
    environment:
      NODE_ENV: test
    image: ffc-ahwr-farmer-apply-development
    container_name: ffc-ahwr-farmer-apply-test
    command: npm run test
    volumes:
      - ./test-output:/home/node/test-output
      - ./babel.config.cjs:/home/node/babel.config.cjs
      - ./jsconfig.json:/home/node/jsconfig.json
      - ./jest.config.cjs:/home/node/jest.config.cjs
