version: '3.9'

services:
  ffc-ahwr-farmer-apply:
    build:
      context: .
      target: production
    image: ffc-ahwr-farmer-apply
    container_name: ffc-ahwr-farmer-apply
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-farmer-apply-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
