services:
  ffc-ahwr-farmer-apply:
    build:
      context: .
      target: production
    image: ffc-ahwr-farmer-apply
    container_name: ffc-ahwr-farmer-apply
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-farmer-apply-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      APPLICATIONREQUEST_QUEUE_ADDRESS: ${APPLICATIONREQUEST_QUEUE_ADDRESS:-ffc-ahwr-application-request}${MESSAGE_QUEUE_SUFFIX}
      APPLICATIONRESPONSE_QUEUE_ADDRESS: ${APPLICATIONRESPONSE_QUEUE_ADDRESS:-ffc-ahwr-application-response}${MESSAGE_QUEUE_SUFFIX}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      EVENT_QUEUE_ADDRESS: ${EVENT_QUEUE_ADDRESS:-ffc-ahwr-event}${MESSAGE_QUEUE_SUFFIX}
      GOOGLE_TAG_MANAGER_KEY: ${GOOGLE_TAG_MANAGER_KEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      SERVICE_URI: http://localhost:3000/apply
      CLAIM_SERVICE_URI: http://localhost:3004/claim
      CUSTOMER_SURVEY_APPLY_URI: ${CUSTOMER_SURVEY_APPLY_URI:-https://forms.office.com/pages/responsepage.aspx?id=UCQKdycCYkyQx044U38RAsIdAEqqafZCk2LjifrI4h1UOUVRSThFNEE1RFdWRVk5U0VGSUM3SDcyNi4u&route=shorturl}
      URL_PREFIX: "/apply"
      APPLICATION_API_URI: http://host.docker.internal:3001/api
      RPA_HOST_NAME: ${RPA_HOST_NAME:-https://dev-internal-gateway.trade.azure.defra.cloud}
      RPA_GET_PERSON_SUMMARY_URL: ${RPA_GET_PERSON_SUMMARY_URL:-/rural-payments-vet-visits/v1/person/3337243/summary}
      RPA_GET_ORGANISATION_PERMISSIONS_URL: ${RPA_GET_ORGANISATION_PERMISSIONS_URL:-/rural-payments-vet-visits/v1/SitiAgriApi/authorisation/organisation/organisationId/authorisation}
      RPA_GET_ORGANISATION_URL: ${RPA_GET_ORGANISATION_URL:-/rural-payments-vet-visits/v1/organisation/organisationId}
      RPA_GET_CPH_NUMBERS_URL: ${RPA_GET_CPH_NUMBERS_URL:-/rural-payments-vet-visits/v1/SitiAgriApi/cph/organisation/organisationId/cph-numbers}
      APIM_OCP_SUBSCRIPTION_KEY: ${APIM_OCP_SUBSCRIPTION_KEY:-changeme}
      APIM_HOST_NAME: ${APIM_HOST_NAME:-https://login.microsoftonline.com}
      APIM_OAUTH_PATH: ${APIM_OAUTH_PATH:-/c9d74090-b4e6-4b04-981d-e6757a160812/oauth2/v2.0/token}
      APIM_CLIENT_ID: ${APIM_CLIENT_ID:-changeme}
      APIM_CLIENT_SECRET: ${APIM_CLIENT_SECRET:-changeme}
      APIM_SCOPE: ${APIM_SCOPE:-api://dev-futuretrade-int.defra.gov.uk/.default}
      TERMS_AND_CONDITIONS_URL: ${TERMS_AND_CONDITIONS_URL:-http://localhost:3000/apply/terms/v3}
      MULTI_HERDS_ENABLED: ${MULTI_HERDS_ENABLED:-false}
