version: '3.8'

services:
  ffc-ahwr-farmer-apply:
    build:
      context: .
      target: production
    image: ffc-ahwr-farmer-apply
    container_name: ffc-ahwr-farmer-apply
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-farmer-apply-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      APPLICATIONREQUEST_QUEUE_ADDRESS: ${APPLICATIONREQUEST_QUEUE_ADDRESS:-ffc-ahwr-application-request}${MESSAGE_QUEUE_SUFFIX}
      APPLICATIONRESPONSE_QUEUE_ADDRESS: ${APPLICATIONRESPONSE_QUEUE_ADDRESS:-ffc-ahwr-application-response}${MESSAGE_QUEUE_SUFFIX}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      EVENT_QUEUE_ADDRESS: ${EVENT_QUEUE_ADDRESS:-ffc-ahwr-event}${MESSAGE_QUEUE_SUFFIX}
      GOOGLE_TAG_MANAGER_KEY: ${GOOGLE_TAG_MANAGER_KEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY:-examplekey-644a2a30-7487-4e98-a908-b5ecd82d5225-644a2a30-7487-4e98-a908-b5ecd82d5225}
      NOTIFY_TEMPLATE_ID_FARMER_APPLY_LOGIN: ${NOTIFY_TEMPLATE_ID_FARMER_APPLY_LOGIN:-644a2a30-7487-4e98-a908-b5ecd82d5225}
      NOTIFY_TEMPLATE_ID_FARMER_REGISTER_INTEREST: ${NOTIFY_TEMPLATE_ID_FARMER_REGISTER_INTEREST:-d4d9f03d-fa93-4ca7-b404-be93559af657}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REGISTER_YOUR_INTEREST_REQUEST_QUEUE_ADDRESS: ${REGISTER_YOUR_INTEREST_REQUEST_QUEUE_ADDRESS:-ffc-ahwr-register-your-interest-request}${MESSAGE_QUEUE_SUFFIX}
      SERVICE_URI: http://localhost:3000/apply
      CLAIM_SERVICE_URI: http://localhost:3004/claim
      TEST_TOKEN: 
      URL_PREFIX: "/apply"
      REGISTER_YOUR_INTEREST_ENABLED: ${REGISTER_YOUR_INTEREST_ENABLED:-true}
      ELIGIBILITY_API_ENABLED: ${ELIGIBILITY_API_ENABLED:-true}
      ELIGIBILITY_API_URI: http://host.docker.internal:3010/api
      APPLICATION_API_URI: http://host.docker.internal:3001/api
      SELECT_YOUR_BUSINESS_ENABLED: ${SELECT_YOUR_BUSINESS_ENABLED:-false}
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
