environment: development
name: ffc-ahwr-farmer-apply
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-farmer-apply

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-ahwr-farmer-apply-config-map

containerSecret:
  name: ffc-ahwr-farmer-apply-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  googleTagManagerKey:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000
  redisHostname: redis-hostname.default
  redisPartition: ffc-ahwr-frontend
  redisPassword: redis
  redisPort: 6379
  serviceUri:

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
