{{- include "ffc-helm-library.container-config-map" (list . "ffc-ahwr-farmer-apply.config-map") -}}
{{- define "ffc-ahwr-farmer-apply.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  NAMESPACE: {{ quote .Values.namespace }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  APPLICATIONREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationRequestQueueAddress }}
  APPLICATIONRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.applicationResponseQueueAddress }}
  EVENT_QUEUE_ADDRESS: {{ .Values.container.eventQueueAddress }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  {{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  {{- end }}
  {{- if .Values.pr }}
  REDIS_PARTITION: {{ .Values.container.redisPartition }}-{{ .Values.pr }}
  {{ else }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
  {{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  SERVICE_URI: {{ quote .Values.container.serviceUri }}
  CLAIM_SERVICE_URI: {{ quote .Values.container.claimServiceUri }}
  CUSTOMER_SURVEY_APPLY_URI: {{ quote .Values.container.customerSurveyApplyUri }}
  DASHBOARD_SERVICE_URI: {{ quote .Values.container.dashboardServiceUri }}
  URL_PREFIX: {{ quote .Values.container.urlPrefix }}
  APPLICATION_API_URI: {{ quote .Values.container.applicationApiUri }}
  WRECK_HTTP_TIMEOUT_MILLISECONDS: {{ quote .Values.wreckHttp.timeoutMilliseconds }}
  TERMS_AND_CONDITIONS_URL: {{ quote .Values.container.termsAndConditionsUrl }}
{{- end -}}
