{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-farmer-apply.container-secret") -}}
{{- define "ffc-ahwr-farmer-apply.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
  DEFRA_ID_CLIENT_SECRET: {{ .Values.container.defraIdClientSecret | quote }}
{{- end -}}
