{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-farmer-apply.container-secret") -}}
{{- define "ffc-ahwr-farmer-apply.container-secret" -}}
stringData:
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  {{- if .Values.appInsights.key }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
{{- end -}}
